### ISSUE TITLE
Module uses deprecated Dependencies tag

### ISSUE THREAD

**Issue by MrZeyami** [Nordiii/SoundTimeToStreamSettings#1]
Throws an error in foundry right now, supposedly will cause issues in later versions if left in.
![image](https://github.com/Nordiii/audio-duration-until-stream-setting/assets/40355333/85bb58de-ccd8-400c-a2fb-6ba188a4eef1)

**Comment by Anvillior** [comment]
> Throws an error in foundry right now, supposedly will cause issues in later versions if left in. ![image](https://private-user-images.githubusercontent.com/40355333/294618885-85bb58de-ccd8-400c-a2fb-6ba188a4eef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzk3MjAsIm5iZiI6MTcyMTAzOTQyMCwicGF0aCI6Ii80MDM1NTMzMy8yOTQ2MTg4ODUtODViYjU4ZGUtY2NkOC00MDBjLWEyZmItNmJhMTg4YTRlZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGRlNjk1ZTc0ZDg1YzIzMTJhMmZlYWNhNzhmZTU2ZjY2NmE4MWI2ODk4ZWM0YzJhNWVkNjZjYjQ2YWRmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jmf_UmMUQ1LgxA-YWEWMZWgLIaGvkiOnx57RaagaKuI)

Is this still an issue? I updated to v12 and my players couldn't hear my music until I left a track looping for like 20 minutes.

**Comment by Nordiii** [comment]
> > Throws an error in foundry right now, supposedly will cause issues in later versions if left in. ![image](https://private-user-images.githubusercontent.com/40355333/294618885-85bb58de-ccd8-400c-a2fb-6ba188a4eef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzk3MjAsIm5iZiI6MTcyMTAzOTQyMCwicGF0aCI6Ii80MDM1NTMzMy8yOTQ2MTg4ODUtODViYjU4ZGUtY2NkOC00MDBjLWEyZmItNmJhMTg4YTRlZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGRlNjk1ZTc0ZDg1YzIzMTJhMmZlYWNhNzhmZTU2ZjY2NmE4MWI2ODk4ZWM0YzJhNWVkNjZjYjQ2YWRmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jmf_UmMUQ1LgxA-YWEWMZWgLIaGvkiOnx57RaagaKuI)
> 
> Is this still an issue? I updated to v12 and my players couldn't hear my music until I left a track looping for like 20 minutes.

Hello, this warning should cause no issue in V12. But I did not check if the Module works in V12 yet as my world all use v11 or v10. I will look into it today.

**Comment by Nordiii** [comment]
@Anvillior fixed the module for Foundry V12, should now work properly.

**Comment by Anvillior** [comment]
> @Anvillior fixed the module for Foundry V12, should now work properly.

Glad to hear it, and thanks for being so fast!
